#Create a ubuntu base image with python 3 installed.
FROM python:3

#Set the working directory
WORKDIR /usr/src/app
COPY . .
RUN apt-get -y update
RUN pip3 install -r requirements.txt
EXPOSE 5000
CMD ["python3", "./server.py"]